version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - '16686:16686'
      - '14250:14250'
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  otel-collector:
    image: otel/opentelemetry-collector:0.92.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - '4317:4317'
      - '9464:9464'
    depends_on:
      - jaeger

  prometheus:
    image: prom/prometheus:v2.45.0
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    depends_on:
      - otel-collector

  harness:
    image: arm64v8/alpine:latest
    depends_on:
      - otel-collector
    volumes:
      - ./bin/diffharness:/app/diffharness
    entrypoint: ["/app/diffharness", "-jaeger=otel-collector:4317"]
