version: '3.8'
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.92.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector.yaml
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:2.3.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml

  prometheus:
    image: prom/prometheus:v3.5.0
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    depends_on:
      - otel-collector

  harness:
    image: arm64v8/alpine:latest
    depends_on:
      - otel-collector
    volumes:
      - ./bin/diffharness:/app/diffharness
    ports:
      - '6060:6060'
    entrypoint: ["/app/diffharness", "-telemetry-exporter-endpoint=otel-collector:4317"]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:12.1.1
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - prometheus
