{
 "title": "RinDB - Diffharness Testing",
 "time": { "from": "2025-09-21T04:58:28.828Z", "to": "2025-09-21T05:05:50.716Z" },
 "panels": [
  {
   "title": "Tracing",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "4eead5ca", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{}",
     "tableType": "traces"
    }
   ]
  },
  { "title": "Instance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage (Rate of CPU seconds used)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"harness\"}[$__rate_interval])) by (container_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"harness\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O (Read Bytes Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{container_label_com_docker_compose_service=\"harness\"}[$__rate_interval])) by (container_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Working Set Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container_label_com_docker_compose_service=\"harness\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RinDB Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of `Get` calls made to RinDB.",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "        rate(rindb_get_calls_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total number of `IRange` (iterator range) calls made to RinDB.",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "targets": [
      {
       "expr": "        rate(rindb_irange_calls_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total number of `Remove` calls made to RinDB.",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "        rate(rindb_remove_calls_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total number of `Put` calls made to RinDB.",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
     "targets": [
      {
       "expr": "        rate(rindb_put_calls_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total number of flushes performed.",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "rate(rindb_flush_count_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "WAL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total bytes currently in WAL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "    sum by (job) (rindb_wal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total records currently in WAL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "    sum by (job) (rindb_wal_records)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of append operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "    sum by (job) (rate(rindb_wal_append_duration_milliseconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of records appended/removed from WAL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "expr": "    sum by (job) (rate(rindb_wal_records[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total append duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "    sum by (job) (rate(rindb_wal_append_duration_milliseconds_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average append duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "    sum by (job) (rate(rindb_wal_append_duration_milliseconds_sum[$__rate_interval])) / sum by (job) (rate(rindb_wal_append_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th percentile append duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "    histogram_quantile(0.99, sum by (le, job) (rate(rindb_wal_append_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of bytes written to WAL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "targets": [
    {
     "expr": "    sum by (job) (rate(rindb_wal_bytes[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SSTable Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Total Flush Operations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rindb_sstable_flush_latency_milliseconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Flush Latency (sum of all latencies)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rindb_sstable_flush_latency_milliseconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Flush Latency (milliseconds per operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(rindb_sstable_flush_latency_milliseconds_sum[$__rate_interval]) / rate(rindb_sstable_flush_latency_milliseconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile Flush Latency (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(rindb_sstable_flush_latency_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Flush I/O Bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rindb_sstable_flush_io_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Get Value Operations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rindb_sstable_get_value_latency_milliseconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Get Value Latency (milliseconds per operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "rate(rindb_sstable_get_value_latency_milliseconds_sum[$__rate_interval]) / rate(rindb_sstable_get_value_latency_milliseconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile Get Value Latency (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 53 },
   "targets": [
    {
     "expr": "     histogram_quantile(0.90, sum by(le) (rate(rindb_sstable_get_value_latency_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Get Value I/O Bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rindb_sstable_get_value_io_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flush Operations Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "rate(rindb_sstable_flush_latency_milliseconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Value Operations Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "rate(rindb_sstable_get_value_latency_milliseconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flush I/O Bytes Rate (bytes per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "rate(rindb_sstable_flush_io_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Value I/O Bytes Rate (bytes per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "     rate(rindb_sstable_get_value_io_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SSTable Manager Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Total Add SSTable Operations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "     rindb_sstablemgmt_add_latency_milliseconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Add SSTable Latency (sum of all latencies)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "     rindb_sstablemgmt_add_latency_milliseconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile Add SSTable Latency (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "     histogram_quantile(0.90, sum by(le) (rate(rindb_sstablemgmt_add_latency_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Add SSTable Latency (milliseconds per operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 78 },
   "targets": [
    {
     "expr": "rate(rindb_sstablemgmt_add_latency_milliseconds_sum[$__rate_interval]) / rate(rindb_sstablemgmt_add_latency_milliseconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Add SSTable Calls",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rindb_sstablemgmt_add_calls_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Compact Operations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rindb_sstablemgmt_compact_latency_milliseconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Add SSTable Operations Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "rate(rindb_sstablemgmt_add_latency_milliseconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Add SSTable Calls Rate (calls per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 86 },
   "targets": [
    {
     "expr": "rate(rindb_sstablemgmt_add_calls_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Get Relevant Operations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "     rindb_sstablemgmt_get_relevant_latency_milliseconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Compact Latency (sum of all latencies)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rindb_sstablemgmt_compact_latency_milliseconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compact Operations Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "rate(rindb_sstablemgmt_compact_latency_milliseconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Relevant Operations Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 94 },
   "targets": [
    {
     "expr": "     rate(rindb_sstablemgmt_get_relevant_latency_milliseconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Get Relevant Latency (sum of all latencies)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "     rindb_sstablemgmt_get_relevant_latency_milliseconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile Compact Latency (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "     histogram_quantile(0.90, sum by(le) (rate(rindb_sstablemgmt_compact_latency_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Get Relevant Latency (milliseconds per operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "     rate(rindb_sstablemgmt_get_relevant_latency_milliseconds_sum[$__rate_interval]) / rate(rindb_sstablemgmt_get_relevant_latency_milliseconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Compact Latency (milliseconds per operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 102 },
   "targets": [
    {
     "expr": "rate(rindb_sstablemgmt_compact_latency_milliseconds_sum[$__rate_interval]) / rate(rindb_sstablemgmt_compact_latency_milliseconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Table Cache Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Total opens",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rindb_tablecache_opens_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total closes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rindb_tablecache_closes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rate of opens per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "rate(rindb_tablecache_opens_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of closes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 111 },
   "targets": [
    {
     "expr": "rate(rindb_tablecache_closes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total hits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rindb_tablecache_hits_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total promotions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rindb_tablecache_promotions_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of hits per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 119 },
   "targets": [
    {
     "expr": "rate(rindb_tablecache_hits_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of promotions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 119 },
   "targets": [
    {
     "expr": "rate(rindb_tablecache_promotions_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}